group: travis_latest
language: python
cache: pip
python:
    - 2.7
    - 3.6
install:
    #- pip install -r requirements.txt
    - pip install flake8 pytest  # add another testing frameworks later
before_script:
    - EXCLUDE=./generated/2.2,./generator/templates
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --exclude=$EXCLUDE --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exclude=$EXCLUDE --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - pytest --capture=sys  # add other tests here
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
